# Generated by Django 4.1.6 on 2023-02-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('profissao', models.CharField(max_length=100)),
                ('salario', models.FloatField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Ferminino')], max_length=1)),
            ],
        ),
    ]
